"""added a comment table

Revision ID: 3df60af846c5
Revises: 5e1775e340b4
Create Date: 2026-07-23 13:19:16.175609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df60af846c5'
down_revision = '5e1775e340b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], name=op.f('fk_comments_article_id_articles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('admin', 'author', 'user'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'author', 'user'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.drop_table('comments')
    # ### end Alembic commands ###
