"""relationship setting

Revision ID: 5e1775e340b4
Revises: 9ce8f3dfdc1e
Create Date: 2026-07-22 13:58:54.776587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1775e340b4'
down_revision = '9ce8f3dfdc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_follows_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_follows_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_follows'))
    )
    op.drop_table('follow')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_profile_user_id'), ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_profile_user_id_users'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('reaction_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_reactions_article_id_articles'), 'articles', ['article_id'], ['article_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reactions_article_id_articles'), type_='foreignkey')
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reaction_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_profile_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_profile_user_id'), type_='unique')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('view_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('follow',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_follow_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_follow_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_follow'))
    )
    op.drop_table('follows')
    # ### end Alembic commands ###
