"""started the migration process

Revision ID: 905571fc3bb3
Revises: 
Create Date: 2026-07-20 14:08:56.546168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905571fc3bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('category_name', name=op.f('uq_categories_category_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('cover_image', sa.String(length=100), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name=op.f('fk_articles_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_articles_category_id_categories')),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_articles')),
    sa.UniqueConstraint('title', name=op.f('uq_articles_title'))
    )
    op.create_table('follow',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_follow_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_follow_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_follow'))
    )
    op.create_table('reactions',
    sa.Column('reaction_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('reaction_type', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_reactions_user_id_users')),
    sa.PrimaryKeyConstraint('reaction_id', name=op.f('pk_reactions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('follow')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
