"""added a profile table

Revision ID: 9ce8f3dfdc1e
Revises: 905571fc3bb3
Create Date: 2026-07-22 09:50:35.459345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce8f3dfdc1e'
down_revision = '905571fc3bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('gender')
        batch_op.drop_column('bio')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=400), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=True))

    op.drop_table('profile')
    # ### end Alembic commands ###
