"""initial migration

Revision ID: a6ac62301ebe
Revises: 
Create Date: 2026-07-28 14:43:39.086430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac62301ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('category_name', name=op.f('uq_categories_category_name'))
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('cover_image', sa.String(length=100), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name=op.f('fk_articles_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_articles_category_id_categories')),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_articles')),
    sa.UniqueConstraint('title', name=op.f('uq_articles_title'))
    )
    op.create_table('follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_follows_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_follows_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_follows'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.String(length=400), nullable=False),
    sa.Column('role', sa.Enum('admin', 'author', 'user', name='user_roles'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_profile_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profile_user_id'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], name=op.f('fk_comments_article_id_articles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_comments'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'LIVE', 'FINISHED', name='match_status'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('minute', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_matches_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('reactions',
    sa.Column('reaction_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('reaction_type', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], name=op.f('fk_reactions_article_id_articles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_reactions_user_id_users')),
    sa.PrimaryKeyConstraint('reaction_id', name=op.f('pk_reactions'))
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=False),
    sa.Column('predicted_away_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CORRECT', 'INCORRECT', name='prediction_status'), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_predictions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('reactions')
    op.drop_table('matches')
    op.drop_table('comments')
    op.drop_table('teams')
    op.drop_table('profile')
    op.drop_table('follows')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('leagues')
    op.drop_table('categories')
    # ### end Alembic commands ###
